<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ProUser\Module'                        => __DIR__ . '/Module.php',
    'ProUser\Controller\UserController' => __DIR__ . '/src/ProUser/Controller/UserController.php',
    'ProUserTest\Framework\TestCase'        => __DIR__ . '/tests/ProUser/Framework/TestCase.php',
    'ProUserTest\SampleTest'                => __DIR__ . '/tests/ProUser/SampleTest.php',
);
