<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ProLdap\Module'                        => __DIR__ . '/Module.php',
    'ProLdap\Controller\LdapController' => __DIR__ . '/src/ProLdap/Controller/LdapController.php',
    'ProLdapTest\Framework\TestCase'        => __DIR__ . '/tests/ProLdap/Framework/TestCase.php',
    'ProLdapTest\SampleTest'                => __DIR__ . '/tests/ProLdap/SampleTest.php',
);
